"""fixing naming dass42

Revision ID: d6186824e10b
Revises: 
Create Date: 2025-11-15 00:44:08.349680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6186824e10b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('dass21',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dass21_id'), 'dass21', ['id'], unique=False)
    op.create_table('dass42',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dass42_id'), 'dass42', ['id'], unique=False)
    op.create_table('severity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_severity_id'), 'severity', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'expert', name='roleenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('severity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['severity_id'], ['severity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conclusions_id'), 'conclusions', ['id'], unique=False)
    op.create_table('expert_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('publication_count', sa.Integer(), nullable=True),
    sa.Column('patient_count', sa.Integer(), nullable=True),
    sa.Column('flight_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('expert_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('education_weight', sa.Integer(), nullable=True),
    sa.Column('patient_weight', sa.Integer(), nullable=True),
    sa.Column('publication_weight', sa.Integer(), nullable=True),
    sa.Column('flight_hours_weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dass21_id', sa.Integer(), nullable=True),
    sa.Column('percent_anxiety', sa.Integer(), nullable=True),
    sa.Column('percent_depression', sa.Integer(), nullable=True),
    sa.Column('percent_stress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dass21_id'], ['dass21.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_id'), 'preferences', ['id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conclusion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conclusion_id'], ['conclusions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_table('premise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dass42_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.Enum('no_prefix', 'not_', name='prefixenum'), nullable=True),
    sa.Column('conjunction', sa.Enum('and_', 'or_', 'then', name='conjunctionenum'), nullable=True),
    sa.Column('level', sa.Enum('low', 'med', 'high', name='levelenum'), nullable=True),
    sa.ForeignKeyConstraint(['dass42_id'], ['dass42.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premise_id'), 'premise', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_premise_id'), table_name='premise')
    op.drop_table('premise')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_preferences_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_table('expert_weights')
    op.drop_table('expert_profiles')
    op.drop_index(op.f('ix_conclusions_id'), table_name='conclusions')
    op.drop_table('conclusions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_severity_id'), table_name='severity')
    op.drop_table('severity')
    op.drop_index(op.f('ix_dass42_id'), table_name='dass42')
    op.drop_table('dass42')
    op.drop_index(op.f('ix_dass21_id'), table_name='dass21')
    op.drop_table('dass21')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
